# SKILLS = [
#     "Java",
#     "Python",
#     "JavaScript",
#     "TypeScript",
#     "HTML",
#     "CSS",
#     "Angular",
#     "React",
#     "Spring Boot",
#     "SQL",
#     "MySQL",
#     "PostgreSQL",
#     "REST API",
#     "API Testing",
#     "Git",
#     "Docker",
#     "Kubernetes",
#     "Linux",
#     "AWS",
#     "Azure",
#     "DevOps",
#     "Machine Learning",
#     "Data Science"
# ]


# SKILL_KEYS = {
#     "Java": "java_skill",
#     "Python": "python_skill",
#     "JavaScript": "javascript_skill",
#     "TypeScript": "typescript_skill",
#     "HTML": "html_skill",
#     "CSS": "css_skill",
#     "Angular": "angular_skill",
#     "React": "react_skill",
#     "Spring Boot": "spring_boot_skill",
#     "SQL": "sql_skill",
#     "MySQL": "mysql_skill",
#     "PostgreSQL": "postgresql_skill",
#     "REST API": "rest_api_skill",
#     "API Testing": "api_testing_skill",
#     "Git": "git_skill",
#     "Docker": "docker_skill",
#     "Kubernetes": "kubernetes_skill",
#     "Linux": "linux_skill",
#     "AWS": "aws_skill",
#     "Azure": "azure_skill",
#     "DevOps": "devops_skill",
#     "Machine Learning": "machine_learning_skill",
#     "Data Science": "data_science_skill"
# }

SKILLS = [
    "Java",
    "Python",
    "Kafka",
    "SQL",
    "Docker",
    "Kubernetes",
    "Spring Boot",
    "FastAPI",
    "PostgreSQL",
    "AWS",
    "Machine Learning",
    "Data Science",
    "Angular",
    "React",
    "Git",
    "Linux",
    "REST API",
    "Microservices",
    "Redis",
    "MongoDB",
    "HTML",
    "CSS",
    "JavaScript"
]