spring.application.name=enroll-service

server.port=8083

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://127.0.0.1:5432/learning_platform_enrollment}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:learning_admin}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:learning_password}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

# JWT
jwt.secret=${JWT_SECRET:learning-platform-secret-key-change-this-in-production-123456789}
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always
course-service.url=${COURSE_SERVICE_URL:http://course-service:8082}

# =========================
# KAFKA
# =========================

spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP_SERVERS:kafka:9092}
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
spring.kafka.producer.properties.spring.json.add.type.headers=false