spring.application.name=api-gateway

server.port=8080


# =========================================================
# USER SERVICE
# =========================================================

spring.cloud.gateway.server.webflux.routes[0].id=user-service
spring.cloud.gateway.server.webflux.routes[0].uri=http://user-service:8081
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/api/users/**


# =========================================================
# AUTH SERVICE
# =========================================================

spring.cloud.gateway.server.webflux.routes[1].id=auth-service
spring.cloud.gateway.server.webflux.routes[1].uri=http://user-service:8081
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/api/auth/**


# =========================================================
# COURSE SERVICE
# =========================================================

spring.cloud.gateway.server.webflux.routes[2].id=course-service
spring.cloud.gateway.server.webflux.routes[2].uri=http://course-service:8082
spring.cloud.gateway.server.webflux.routes[2].predicates[0]=Path=/api/courses/**

# =========================================================
# INSTRUCTOR COURSES
# =========================================================

spring.cloud.gateway.server.webflux.routes[11].id=instructor-course-service
spring.cloud.gateway.server.webflux.routes[11].uri=http://course-service:8082
spring.cloud.gateway.server.webflux.routes[11].predicates[0]=Path=/api/instructor/courses/**

# =========================================================
# QUIZ / QUESTION SERVICE
# =========================================================

spring.cloud.gateway.server.webflux.routes[12].id=quiz-service
spring.cloud.gateway.server.webflux.routes[12].uri=http://course-service:8082
spring.cloud.gateway.server.webflux.routes[12].predicates[0]=Path=/api/quizzes/**

# =========================================================
# ENROLLMENT SERVICE
# =========================================================

spring.cloud.gateway.server.webflux.routes[3].id=enrollment-service
spring.cloud.gateway.server.webflux.routes[3].uri=http://enroll-service:8083
spring.cloud.gateway.server.webflux.routes[3].predicates[0]=Path=/api/enrollments/**


# =========================================================
# PROGRESS SERVICE
# =========================================================

spring.cloud.gateway.server.webflux.routes[4].id=progress-service
spring.cloud.gateway.server.webflux.routes[4].uri=http://enroll-service:8083
spring.cloud.gateway.server.webflux.routes[4].predicates[0]=Path=/api/progress/**


# =========================================================
# QUIZ ATTEMPTS
# =========================================================

spring.cloud.gateway.server.webflux.routes[5].id=quiz-attempt-service
spring.cloud.gateway.server.webflux.routes[5].uri=http://enroll-service:8083
spring.cloud.gateway.server.webflux.routes[5].predicates[0]=Path=/api/quiz-attempts/**


# =========================================================
# CERTIFICATES
# =========================================================

spring.cloud.gateway.server.webflux.routes[6].id=certificate-service
spring.cloud.gateway.server.webflux.routes[6].uri=http://enroll-service:8083
spring.cloud.gateway.server.webflux.routes[6].predicates[0]=Path=/api/certificates/**


# =========================================================
# INTERNAL ENROLLMENT / PROGRESS
# =========================================================

spring.cloud.gateway.server.webflux.routes[7].id=internal-enrollment-service
spring.cloud.gateway.server.webflux.routes[7].uri=http://enroll-service:8083
spring.cloud.gateway.server.webflux.routes[7].predicates[0]=Path=/api/internal/**


# =========================================================
# ADMIN ENROLLMENTS
# =========================================================

spring.cloud.gateway.server.webflux.routes[8].id=admin-enrollment-service
spring.cloud.gateway.server.webflux.routes[8].uri=http://enroll-service:8083
spring.cloud.gateway.server.webflux.routes[8].predicates[0]=Path=/api/admin/enrollments/**


# =========================================================
# REPORTING SERVICE
# =========================================================

spring.cloud.gateway.server.webflux.routes[9].id=reporting-service
spring.cloud.gateway.server.webflux.routes[9].uri=http://reporting-service:8001
spring.cloud.gateway.server.webflux.routes[9].predicates[0]=Path=/api/reports/**


# =========================================================
# RECOMMENDATION SERVICE
# =========================================================

spring.cloud.gateway.server.webflux.routes[10].id=recommendation-service
spring.cloud.gateway.server.webflux.routes[10].uri=http://recommendation-service:8000
spring.cloud.gateway.server.webflux.routes[10].predicates[0]=Path=/api/recommendations/**

# =========================================================
# QUESTION / OPTIONS SERVICE
# =========================================================

spring.cloud.gateway.server.webflux.routes[13].id=question-service
spring.cloud.gateway.server.webflux.routes[13].uri=http://course-service:8082
spring.cloud.gateway.server.webflux.routes[13].predicates[0]=Path=/api/questions/**

# =========================================================
# ACTUATOR
# =========================================================

management.endpoints.web.exposure.include=health,info,gateway

management.endpoint.gateway.access=read-only

management.endpoint.health.show-details=always


# =========================================================
# CORS
# =========================================================

spring.cloud.gateway.server.webflux.globalcors.add-to-simple-url-handler-mapping=true

spring.cloud.gateway.server.webflux.globalcors.cors-configurations.[/**].allowedOrigins=http://localhost:4200
spring.cloud.gateway.server.webflux.globalcors.cors-configurations.[/**].allowedMethods=GET,POST,PUT,DELETE,OPTIONS
spring.cloud.gateway.server.webflux.globalcors.cors-configurations.[/**].allowedHeaders=*
spring.cloud.gateway.server.webflux.globalcors.cors-configurations.[/**].allowCredentials=true