spring.application.name=course-service

server.port=8082

# PostgreSQL
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://127.0.0.1:5432/learning_platform}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:learning_admin}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:learning_password}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# JWT
jwt.secret=${JWT_SECRET:learning-platform-secret-key-change-this-in-production-123456789}

# User Service
user-service.url=${USER_SERVICE_URL:http://127.0.0.1:8081}
enrollment.service.url=${ENROLLMENT_SERVICE_URL:http://127.0.0.1:8083}